name: cellscan
description: "Collect user and cell tower information for the CellScan project."
publish_to: 'none'

version: 0.7.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cellscan_native:
    path: cellscan_native
  permission_handler: ^11.3.0
  http: ^1.2.0
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.3
  flutter_translate: ^4.0.4
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5
  version: ^3.0.0
  package_info_plus: ^4.2.0
  geolocator: ^11.0.0
  dynamic_color: ^1.7.0
  ota_update: ^6.0.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"