name: cellscan
description: "Collect user and cell tower information for the CellScan project."
publish_to: 'none'

version: 0.4.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.0
  http: ^1.2.0
  sqflite: ^2.3.2
  path: ^1.9.0
  flutter_json_view: ^1.1.4
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.3
  system_theme: ^2.3.1
  flutter_translate: ^4.0.4
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5
  location: ^5.0.0-dev.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/i18n/

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"