name: publish-android-apk
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
          channel: stable
      - run: flutter --version