name: publish-android-apk
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter build apk