name: publish-android-apk
on:
  push:
    branches: [main]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.2
          channel: stable
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Get app version
        run: "echo CELLSCAN_VERSION=v$(cat pubspec.yaml | sed -nr 's/version: *(.+)/\\1/p') >> $GITHUB_ENV"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.CELLSCAN_VERSION }}
          commit: main
          artifacts: build/app/outputs/apk/release/cellscan-v${{ env.CELLSCAN_VERSION }}.apk